#!/bin/bash
## help
## - help for shed
## version 0.0.1 - initial
##################################################
slack-shed-help() {
 cat << EOF
slack-shed

SUBCOMMANDS

	start-date	yyyy-mm-dd
	date-oldest	yyyy-mm-dd

	- get channel histories between now and oldest date

EOF
}
#-------------------------------------------------
#help() {
# true
#}
##################################################
#if [ ${#} -eq 0 ] 
#then
# true
#else
# exit 1 # wrong args
#fi
##################################################
#help
##################################################
## generated by create-stub2.sh v0.1.1
## on Sat, 21 Apr 2018 08:50:43 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
