#!/bin/bash
## testing
## version 0.0.1 - initial
##################################################
# for-each-channel =slack.sh/functions.sh=
# - do something on each channel
# + currently fectching user channel history
# version 0.0.3 - ***
# + new requirements 180418 
# ++ follow-up: make sure ts is converted to date-time 
#    format
# +++ filter
# ++++ users
# +++++ reactions: users
# +++++ replies: users
# ++++ ts
# +++++ edited: ts
# +++++ replies: ts
#-------------------------------------------------
for-each-channel() { { local date_oldest ; date_oldest="${1}" ; }

 ## depreciated may remove later
 #{ local function_name ; function_name="${1}" ; }
 
 local user_channel_history 
 user_channel_history=$( 
  ${FUNCNAME}-get-user-channel-history
 )
 echo ${user_channel_history} | tee temp-user-channel-history 1>&2

 ## get list of unique users
 local unique_users
 unique_users=$(
  echo ${user_channel_history} \
  | jq '.[]["user"]' \
  | sort \
  | uniq \
  | sed -e 's/null//g'
 )
 echo unique_users: ${unique_users} 1>&2

 ## replace user w/ user real_name in user channel history
 local user 
 for user in ${unique_users} 
 do
  echo ${user} 1>&2
  sed -i -e "s/${user}/$( slack-users-info ${user} real-name )/g" temp-user-channel-history
 done
 cat temp-user-channel-history | jq '.' 1>&2

 ## get list of tss
 local tss
 tss=$(
  echo ${user_channel_history} \
  | jq '.[]["ts"]' \
  | sort \
  | uniq \
  | sed -e 's/null//g'
 )
 echo tss: ${tss} 1>&2

 ## replace ts w/ date
 local ts
 local ts_date
 for ts in ${tss}
 do
  echo ${ts} 1>&2
  ts_date=$( date --date="@$( trim ${ts} )" )
  echo ${ts_date} 1>&2
  sed -i -e "s/${ts}/\"${ts_date}\"/g" temp-user-channel-history
 done
 cat temp-user-channel-history | jq '.'
}
#-------------------------------------------------
#testing() {
# true
#}
##################################################
#if [ ${#} -eq 0 ] 
#then
# true
#else
# exit 1 # wrong args
#fi
##################################################
#testing
##################################################
## generated by create-stub2.sh v0.1.1
## on Sat, 21 Apr 2018 09:05:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
