#!/bin/bash
## aliases for shed
## version 0.0.3 - post integration
##################################################
shopt -s expand_aliases
#-------------------------------------------------
alias set-debug='
 echo ${debug} > set-debug
'
#-------------------------------------------------
alias set-output-format='
 echo ${output_format} > set-output
'
#-------------------------------------------------
alias test-the-member-id='
{
  test-member-id ${FUNCNAME} ${member_id}
}
'
#-------------------------------------------------
alias sed-escape-member-id='sed -e "s/\\\\s/ /g"'
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 20:05:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
