#!/bin/bash
## functions-get
## - get functions for shed
## version 0.0.1 - initial
##################################################
slack-shed-get-user-channel-history-for-today() { { local member_id ; member_id="${1}" ; local channel_ids ; channel_ids=${@:2} ; }
  test-member-id
  { 
    slack-shed-get-user-channel-history \
    $( date-today ) \
    ${member_id} \
    ${channel_ids}
  }
}
#-------------------------------------------------
slack-shed-get-user-channel-history() { { local date_oldest ; date_oldest="${1}" ; local member_id ; member_id="${2}" ; local channel_ids ; channel_ids=${@:3} ; }
 test-member-id
 {
   local member_ids
   member_ids="\"${member_id}\""
 }
 slack-shed-date-oldest ${date_oldest} ${channel_ids}
}
#-------------------------------------------------
slack-shed-get() {
 commands
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 20:30:26 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
