#!/bin/bash
## functions-test
## - test functions for shed
## version 0.0.2 - post integration
##################################################
slack-shed-test-get-channel-id-by-name() { { local candidate_value ; candidate_value=${@} ; }
 get-channel-id-by-name ${candidate_value}
}
#-------------------------------------------------
slack-shed-test-get-channel-id() { { local candidate_field ; candidate_field="${1}" ; local candidate_value ; candidate_value=${@:2} ; }
 get-channel-id ${candidate_field} ${candidate_value} 
}
#-------------------------------------------------
slack-shed-test-escape-slash() {
 escape-slash ${@}
}
#-------------------------------------------------
slack-shed-test-get-user-id() {
 get-user-id ${@}
}
#-------------------------------------------------
slack-shed-test-list-users() {
 list-users 
}
#-------------------------------------------------
slack-shed-test-list-channels() {
 list-channels ${@}
}
#-------------------------------------------------
slack-shed-test-get-channel-ids() {
 get-channel-ids | sed-strip-double-quotes
}
#-------------------------------------------------
slack-shed-test() {
 commands
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 20:10:46 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
