#!/bin/bash
## header
## =stub=
## version 0.0.1 - initial
##################################################
test ${#} -eq 1 && {
 shed_source_path="${1}"
true
} || {
 shed_source_path=$( dirname ${0} )
}
. ${shed_source_path}/slack.sh/header.sh ${shed_source_path}/slack.sh
. ${shed_source_path}/functions.sh
. ${shed_source_path}/aliases.sh
. ${shed_source_path}/functions-test.sh
. ${shed_source_path}/functions-set.sh
. ${shed_source_path}/functions-get.sh
unset shed_source_path
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 07 May 2018 10:37:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
