#!/bin/bash
## help
## - help for shed
## version 0.0.2 - get-user-channel-history-for-today
##################################################
slack-shed-help() {
 cat << EOF
slack-shed

SUBCOMMANDS

	start-date	yyyy-mm-dd
	date-oldest	yyyy-mm-dd

	- get channel histories between now and oldest date

EOF
}
#-------------------------------------------------
slack-shed-get-user-channel-history-for-today-help() {
 cat << EOF
shed get user-channel-history-for-today

- return channel history for a single user since beginning of day for one or more channels

shed-get-user-channel-history member_id [channel_ids..]

REQUIRED

1  - member id (U1234567890)

OPTIONAL

2- - channel ids (C123456779889 C..)
EOF
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Sat, 21 Apr 2018 08:50:43 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
