#!/bin/bash
## shed
## - export workdspace slack history
## version 1.0.1 - using header
## requires:
## - slack.sh
##################################################
. $( dirname ${0} )/header.sh $( dirname ${0} )
##################################################
## override default behvior in slack
list-available-commands-filter-exclude-list() { 
 cat << EOF
$( ${FUNCNAME}-default )
date-oldest
EOF
}
#-------------------------------------------------
. $( dirname ${0} )/help.sh
#-------------------------------------------------
. $( dirname ${0} )/entry.sh
#-------------------------------------------------
. $( dirname ${0} )/testing.sh
##################################################
if [ ! ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
shed ${@}
##################################################
## generated by create-stub2.sh v0.1.0
## on Mon, 09 Apr 2018 20:05:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
