#!/bin/bash
## testing
## version 0.1.0 - retrieve user id initial
##################################################
## objective:
## - retrieve user id from real name etc.
#-------------------------------------------------
slack-shed-get-user-id() { { local candidate_field ; local candidate_value ; candidate_field="${1}" ; candidate_value=${@:2} ; }
 get-user-id ${candidate_field} ${candidate_value}
}
#-------------------------------------------------
slack-shed-get-user-id-by() {
 commands
}
#-------------------------------------------------
slack-shed-get-user-id-by-real-name() { { local candidate_realname ; candidate_realname=${@} ; }
 get-user-id real_name ${candidate_realname}
}
#declare -f | grep -e '.*get-user-id.*()'
#read
##################################################
## generated by create-stub2.sh v0.1.1
## on Sat, 21 Apr 2018 09:05:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
