#!/bin/bash
## testing
## version 0.0.0 - empty
#################################################
##
## Use keyword arguments instead of positional 
## arguments
##
## < shed get user-channel-history-for-today "Joe\sSomebody" "general" "random"
##
## > shed get user-channel-history-for-today -u "Joe\sSomebody" -c general -c random
##
##-----------------------------------------------
error "true"
range() { ${SH2}/range.sh ${@} ; }
. ${SH2}/getops.sh
member_id=
channel_ids=
#-------------------------------------------------
on-shortops-case() {
 case ${1} in
  u) { # -u user_name
   member_id="${2}"
   echo 2
  } ;;
  c) { # -u channel_name
   channel_ids="${channel_ids} ${2}"
   echo 2
  }
 esac
}
#-------------------------------------------------
slack-shed-get-user-channel-history-for-today-test() {
 test "${member_id}" || {
  error "member id not specified" "" ""
  false
 }
 test "${channel_ids}" || {
  error "channel ids no specified" "" ""
  false
 }
}
##-----------------------------------------------
# version 0.1.0 - options
slack-shed-get-user-channel-history-for-today() { { getops ${@} ; }

  ${FUNCNAME}-test

  echo testing
  echo member_id: ${member_id}
  echo channel_ids: ${channel_ids}
  read

  ## parse arge

  { 
    slack-shed-get-user-channel-history \
    $( date-today ) #\
    #${member_id} \
    #${channel_ids}
  }

}
#-------------------------------------------------
# version 0.1.0 - inherit member id and channel ids
slack-shed-get-user-channel-history() { { local date_oldest ; date_oldest="${1}" ; getops ${@:2} ; }

  cecho green in ${FUNCNAME}

  {
    cecho yellow member: ${member_id}
    cecho yellow channels: ${channel_ids}
  }
  
  ## pre process member id
  member_id=$( 
   case ${member_id} in
    U*) {
     cecho yellow candidate member id
     echo ${member_id} 
    } ;;
    *) {
     cecho yellow candidate field associated with member id
     ## try to convert associated field to member id
     trim $(
       get-user-id "real_name" "$( member-id-escaped )" ||
       echo ${member_id} # fallback 
     ) 
    } ;;
   esac
  )

  ## pre process channel ids
  channel_ids=$(
  for channel_id in ${channel_ids}
  do
   case ${channel_id} in
   C*) {
    cecho yellow candidate channel id
    echo ${channel_id} 
   } ;;
   *) {
    cecho yellow candidate field associated with channel id
    ## try to convert associated field to channel id
    trim $(
     get-channel-id-by-name "${channel_id}" ||
     echo ${channel_id} # fallback
    )
   } ;;
   esac 
  done
  )

  {
    cecho yellow member: ${member_id}
    cecho yellow channels: ${channel_ids}
  }
 
  cecho green testing member id
  test-the-member-id

  ## may add later
  #test-channel-ids

  {
    local member_ids
    member_ids="\"${member_id}\""
  }

  slack-shed-date-oldest ${date_oldest} ${channel_ids}

}
##################################################
## generated by create-stub2.sh v0.1.1
## on Sat, 21 Apr 2018 09:05:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
